name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git for private repos
        run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: latest

      - name: Run lint
        run: pixi run lint

      - name: Test
        run: pixi run test
